replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/platform-eng-lab-will/coverline/frontend
  tag: "49d1e26aa43ae2b62aa2acac74db8b24660fc5c2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

backendUrl: "http://coverline-backend:5000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
