name: coverline
version: "1.0.0"
profile: coverline

model-paths: ["models"]
test-paths: ["tests"]

models:
  coverline:
    staging:
      +materialized: view
    analytics:
      +materialized: table
