sonar.projectKey=wb-platform-engineering-lab_platform-engineering-lab-gke
sonar.organization=wb-platform-engineering-lab
sonar.sources=phase-3-helm/app
sonar.exclusions=**/node_modules/**,**/*.test.js,**/__pycache__/**
