apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: coverline-frontend
  description: CoverLine member-facing web application
  annotations:
    github.com/project-slug: wb-platform-engineering-lab/platform-engineering-lab-gke
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - frontend
  links:
    - url: https://github.com/wb-platform-engineering-lab/platform-engineering-lab-gke/blob/main/phase-3-helm/app/frontend/
      title: Source Code
spec:
  type: website
  lifecycle: production
  owner: platform-team
  system: coverline-platform
  consumesApis:
    - coverline-claims-api
  dependsOn:
    - component:default/coverline-backend
