replicaCount: 3
image:
  tag: "b1a6af3" # Updated by platform-pipeline promote job
vault:
  enabled: false
resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
