backstage:
  image:
    registry: ghcr.io
    repository: backstage/backstage
    tag: "1.30.2"

  appConfig:
    app:
      title: CoverLine Developer Portal
      baseUrl: http://localhost:7007

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    catalog:
      locations:
        - type: url
          target: https://github.com/wb-platform-engineering-lab/platform-engineering-lab-gke/blob/main/catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location]

    techdocs:
      builder: external
      generator:
        runIn: local
      publisher:
        type: local

    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: gke-dev
              url: https://35.222.47.178
              authProvider: serviceAccount
              skipTLSVerify: false
              # caData and serviceAccountToken injected at install time via --set
              serviceAccountToken: ${K8S_SA_TOKEN}

  extraEnvVarsSecrets:
    - backstage-github-token

postgresql:
  enabled: true
  auth:
    password: backstage-local-dev-only

ingress:
  enabled: false
