replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/platform-eng-lab-will/coverline/frontend
  tag: "b826640d035772bd8a744b19ab90a02cf3ee2a14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

backendUrl: "http://coverline-backend:5000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
