replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/platform-eng-lab-will/coverline/frontend
  tag: "0910281085c3406cf58414ca75a5a867e5ebc846"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

backendUrl: "http://coverline-backend:5000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
