replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/platform-eng-lab-will/coverline/frontend
  tag: "b8ff726a196c357daffed70eab9550f670349bff"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

backendUrl: "http://coverline-backend:5000"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
