apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coverline-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wb-platform-engineering-lab/platform-engineering-lab-gke
    targetRevision: main
    path: phase-4-helm/charts/backend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
